app:
  jwt:
    secret-key: AS3IK293NS392EA31XC3SIE23SO93D

server:
  port: 8000

spring:
  web:
    resources:
      cache.period: 0
      static-locations: file:src/main/resources/static
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates
    suffix: .html
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 10000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/2501_01a_db
    username: root
    password: dreamy
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: 2501_01a_db_cp
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
        rewriteBatchedInserts: true
        rewriteBatchedStatements: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /api-docs
  paths-to-match:
    - /api/**
    - /login
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# logging:
#   level:
#     org.hibernate.SQL: debug